const assert = require('node:assert/strict');
const { JsonRpcTransformers: J } = require('@ckb-ccc/core/advanced');
const { boot } = require('./harness.cjs');
const { flow } = require('./flow.cjs');
const { CKB, STORAGE } = require('./accounting.cjs');
async function main() {
  const h = await boot(); h.actors = [h.admin, h.owner];
  const f = flow(h), m = await f.create(h.getClock() + 10000);
  await f.deposit(m, 0, 0, 100n * CKB, h.owner);
  await f.deposit(m, 1, 0, 300n * CKB, h.admin);
  await f.deposit(m, 2, 1, 200n * CKB, h.owner);
  h.setClock(m.cutoff + 1000); await h.mine(40); await f.report(m);
  const closed = await f.close(m);
  assert.deepEqual(closed.values, [STORAGE + 14850n * CKB / 100n, STORAGE + 44550n * CKB / 100n, STORAGE]);
  const short = closed.tx.clone(); short.outputs[1].capacity -= 1n; short.outputs[0].capacity += 1n;
  await h.rejects('Settlement rejects an underfunded claim', await h.owner.signer.signTransaction(short), 9);
  const cells = await h.commit(h.owner, closed.tx);
  h.record('All entitlements funded atomically', { transaction: closed.tx.hash() });
  await h.commit(h.owner, await h.build(h.owner, [cells[0]], [{ capacity: cells[0].output.capacity, lock: h.admin.lock }], ['0x']));
  h.record('Reserve recovered while all claims remain unspent');
  const a = await f.claim(cells[1], h.owner), b = await f.claim(cells[2], h.admin);
  assert(!a.inputs.some(x => b.inputs.some(y => x.previousOutput.eq(y.previousOutput))));
  const theft = a.clone(); theft.outputs[0].lock = h.admin.lock;
  await h.rejects('Claim cannot redirect payment', await h.owner.signer.signTransaction(theft), 6);
  const skim = a.clone(); skim.outputs[0].capacity -= 1n;
  await h.rejects('Claim must return its entire capacity', await h.owner.signer.signTransaction(skim), 9);
  await h.rpc('send_transaction', [J.transactionFrom(a), 'passthrough']);
  await h.rpc('send_transaction', [J.transactionFrom(b), 'passthrough']);
  await h.commit(h.owner, a, true); await h.commit(h.admin, b, true);
  h.record('Two independent winning claims submitted before either committed', { transactions: [a.hash(), b.hash()] });
  await h.rejects('Claim replay rejected', a, /Resolve failed Unknown/);
  await h.commit(h.owner, await f.claim(cells[3], h.owner)); h.record('Losing claim returns exact storage');
  const v = await f.create(h.getClock() + 10000);
  await f.deposit(v, 0, 1, 100n * CKB);
  await h.rejects('Premature timeout rejected by consensus', (await f.close(v, true)).tx, /Immature.*since requirement/);
  h.setClock(v.cutoff + 21600000 + 1000); await h.mine(40);
  const cancelled = await f.close(v, true), vc = await h.commit(h.owner, cancelled.tx);
  assert.equal(vc[1].output.capacity, STORAGE + 100n * CKB);
  await h.commit(h.owner, await f.claim(vc[1], h.owner));
  h.record('Six-hour timeout refund has no pool dependency or betting fees', { transaction: cancelled.tx.hash() });
  const late = await f.create(h.getClock() - 1000);
  await f.deposit(late, 0, 1, 100n * CKB);
  h.setClock(late.cutoff + 21600000 + 1000); await h.mine(40);
  h.actors = [h.admin];
  const lateClose = await f.close(late, true);
  const lateCells = await h.commit(h.owner, lateClose.tx);
  assert(lateCells[1].output.lock.eq(h.owner.lock));
  assert.equal(lateCells[1].output.capacity, STORAGE + 100n * CKB);
  h.record('Unknown late bettor refund lock recovered from chain history without a database', { transaction: lateClose.tx.hash() });
  await h.finish();
}
main().catch(e => { console.error(e); process.exitCode = 1; });
